menu:
  主页: /
  博客: /archives
  RSS: /atom.xml
  关于: /about

# 侧边栏
widgets:
- search
- introduction
- blog
- tagcloud
- recent_posts
- popular_posts 
- donate
- advertisement


excerpt_link: 阅读全文...

fancybox: true

